Repository CosmoStat/Sparse2D, pull requests merged in 2019-03, with the labels that each got.

#19 Do not include unused header file
  src/libtools/GlobalInc.h
Labels: clean up

#21 Fix errors reported by Clang
  src/libsparse1d/Filter.cc
  src/libtools/IM_Edge.cc
Labels: bug

#20 Run Travis on OS X
  .travis.yml
  CMakeLists.txt
Labels: enhancement

#24 macOS Updates
  .gitignore
  CMakeLists.txt
Labels: enhancement

#25 openmp bug fix and clean up
  CMakeLists.txt
Labels: bug

#26 added bug fix for openmp
  CMakeLists.txt
Labels: bug
